### ISSUE TITLE
?Add warning for pre-'made public' LRGs 

### ISSUE THREAD

**Issue by ghost** [C-Corbin/comfy_BED#10]
LRG XML files can be downloaded before the XML is at the 'made public' stage. They are not considered valid for use at this pre-public stage. Flag this in sequencer logs, add to BED file, or otherwise inform the user if it's possible to extract this data from the XML.

**Comment by ghost** [comment]
LRG_9 used as an example - this is LRG status 'pending' rather than LRG status 'public'.

**Comment by ghost** [comment]
Possible difference between 'pending' and 'public': pending has contact information only in <updatable_annotation> (n=2) while public has contact information in <fixed_annotation> (n=2)?

**Comment by erikwaskiewicz** [comment]
Yea that's the best difference I can see, I've only compared it to LRG_5 and LRG_293 though, I'm not sure how reproducible it is. LRG_5 has one contact, LRG_293 has two, LRG_9 has three I think.
You'd think they'd have a status field!

The only other alternative I can think of is to use the web API. Only problem with this is that the whole program would be dependent on having internet access then. 

There's a query to get the status of an LRG:
https://www.lrg-sequence.org/web-service/ --> Get status of a list of LRGs
