### ISSUE TITLE
Write test for function calculateGenomicPositions()

### ISSUE THREAD

**Issue by ghost** [C-Corbin/comfy_BED#4]
Function test wasn't written during MSc week - short on time.

**Comment by ghost** [comment]
I'm getting an error when I run comfy_BED from command line, python3 venv:

File "comfy_BED.py", line 98, in calculateGenomicPositions
    for item in transcript_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by ghost** [comment]
Consider using the six library to Python3-proof: https://stackoverflow.com/questions/13998492/when-should-iteritems-be-used-instead-of-items

**Comment by erikwaskiewicz** [comment]
That worked, I'll commit it with this branch
